spring:
  application:
    name: invoice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/weijiliang/invoice-config-repo.git
          username: lightswei@163.com
          password: qiqibuaiwo11
          basedir: C:/basedir
  rabbitmq:
    host: 132.232.46.33
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

